name: Generate EPG

on:
  schedule:
    - cron: '0 0 * * *' # codziennie o północy
  workflow_dispatch:

jobs:
  build-epg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install xml2js node-fetch

      - name: Download pltv.xml
        run: |
          curl -o channels.xml https://epg.ovh/pltv.xml

      - name: Generate guide.xml
        run: |
          node generate.js

      - name: Upload guide.xml
        uses: actions/upload-artifact@v4
        with:
          name: guide
          path: ./guide.xml
