name: Generate EPG

on:
  schedule:
    - cron: '0 2 * * *'   # codziennie o 2:00 UTC
  workflow_dispatch:       # możliwość ręcznego uruchomienia

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install xml2js node-fetch
          cd epg && npm install

      - name: Generate guide.xml
        run: |
          node generate.js

      - name: Upload guide.xml
        uses: actions/upload-artifact@v3
        with:
          name: guide
          path: guide.xml
